Parse Current Bench JSON data and generate a cache directory.

  $ caliper parse-cb-json
  $ ls cache/sample/default | wc -l
  15
  $ cat cache/sample/default/1706675457.2
  ((version 0.1) (commit 0fe70a7741f69fb93d79655e35bd976bc6676e10)
   (timestamp 1706675457.2)
   (entries
    (((group_name "Major Collections") (test_name "[Clean] Major Collections")
      (value 35.) (value_type Float))
     ((group_name "Major Collections") (test_name "[Null] Major Collections")
      (value 24.) (value_type Float))
     ((group_name "Major Collections")
      (test_name "[Clean Sandbox] Major Collections") (value 35.)
      (value_type Float))
     ((group_name "Major Collections")
      (test_name "[Null Sandbox] Major Collections") (value 22.)
      (value_type Float))
     ((group_name "System CPU Time") (test_name "[Clean] System CPU Time")
      (value 61.518961) (value_type Float))
     ((group_name "System CPU Time") (test_name "[Null] System CPU Time")
      (value 0.3354768) (value_type Float))
     ((group_name "System CPU Time")
      (test_name "[Null Sandbox] System CPU Time") (value 0.3410492)
      (value_type Float))
     ((group_name "System CPU Time")
      (test_name "[Clean Sandbox] System CPU Time") (value 64.070604)
      (value_type Float))
     ((group_name Misc) (test_name "Size of _boot/dune.exe") (value 25587408.)
      (value_type Float))
     ((group_name "Heap Chunks") (test_name "[Clean] Heap Chunks") (value 34.)
      (value_type Float))
     ((group_name "Heap Chunks") (test_name "[Null] Heap Chunks") (value 23.)
      (value_type Float))
     ((group_name "Heap Chunks") (test_name "[Clean Sandbox] Heap Chunks")
      (value 34.) (value_type Float))
     ((group_name "Heap Chunks") (test_name "[Null Sandbox] Heap Chunks")
      (value 23.) (value_type Float))
     ((group_name "Minor Words") (test_name "[Clean Sandbox] Minor Words")
      (value 250248885.) (value_type Float))
     ((group_name "Minor Words") (test_name "[Clean] Minor Words")
      (value 237257913.) (value_type Float))
     ((group_name "Minor Words") (test_name "[Null Sandbox] Minor Words")
      (value 180602451.) (value_type Float))
     ((group_name "Minor Words") (test_name "[Null] Minor Words")
      (value 180601961.8) (value_type Float))
     ((group_name "Largest Free") (test_name "[Null Sandbox] Largest Free")
      (value 787456.) (value_type Float))
     ((group_name "Largest Free") (test_name "[Clean] Largest Free")
      (value 930304.) (value_type Float))
     ((group_name "Largest Free") (test_name "[Null] Largest Free")
      (value 787456.) (value_type Float))
     ((group_name "Largest Free") (test_name "[Clean Sandbox] Largest Free")
      (value 930304.) (value_type Float))
     ((group_name "Major Words") (test_name "[Clean Sandbox] Major Words")
      (value 33695033.) (value_type Float))
     ((group_name "Major Words") (test_name "[Clean] Major Words")
      (value 32498917.) (value_type Float))
     ((group_name "Major Words") (test_name "[Null] Major Words")
      (value 18384933.6) (value_type Float))
     ((group_name "Major Words") (test_name "[Null Sandbox] Major Words")
      (value 18383047.4) (value_type Float))
     ((group_name "Free Words") (test_name "[Clean] Free Words")
      (value 7298890.) (value_type Float))
     ((group_name "Free Words") (test_name "[Clean Sandbox] Free Words")
      (value 7298860.) (value_type Float))
     ((group_name "Free Words") (test_name "[Null Sandbox] Free Words")
      (value 2335239.2) (value_type Float))
     ((group_name "Free Words") (test_name "[Null] Free Words")
      (value 2335270.6) (value_type Float))
     ((group_name "User CPU Time") (test_name "[Null] User CPU Time")
      (value 3.276746) (value_type Float))
     ((group_name "User CPU Time") (test_name "[Null Sandbox] User CPU Time")
      (value 3.1928824) (value_type Float))
     ((group_name "User CPU Time") (test_name "[Clean] User CPU Time")
      (value 254.600946) (value_type Float))
     ((group_name "User CPU Time") (test_name "[Clean Sandbox] User CPU Time")
      (value 256.643562) (value_type Float))
     ((group_name "Live Blocks") (test_name "[Null] Live Blocks")
      (value 3126398.) (value_type Float))
     ((group_name "Live Blocks") (test_name "[Null Sandbox] Live Blocks")
      (value 3126410.) (value_type Float))
     ((group_name "Live Blocks") (test_name "[Clean] Live Blocks")
      (value 3124953.) (value_type Float))
     ((group_name "Live Blocks") (test_name "[Clean Sandbox] Live Blocks")
      (value 3124965.) (value_type Float))
     ((group_name "Free Blocks") (test_name "[Clean Sandbox] Free Blocks")
      (value 26.) (value_type Float))
     ((group_name "Free Blocks") (test_name "[Null] Free Blocks") (value 8.)
      (value_type Float))
     ((group_name "Free Blocks") (test_name "[Clean] Free Blocks") (value 26.)
      (value_type Float))
     ((group_name "Free Blocks") (test_name "[Null Sandbox] Free Blocks")
      (value 8.) (value_type Float))
     ((group_name "Build Time") (test_name "[Null Sandbox] Build Time")
      (value 3.53755078316) (value_type Float))
     ((group_name "Build Time") (test_name "[Clean] Build Time")
      (value 316.880563974) (value_type Float))
     ((group_name "Build Time") (test_name "[Null] Build Time")
      (value 3.61568250656) (value_type Float))
     ((group_name "Build Time") (test_name "[Clean Sandbox] Build Time")
      (value 321.460196972) (value_type Float))
     ((group_name "Live Words") (test_name "[Null Sandbox] Live Words")
      (value 14540786.) (value_type Float))
     ((group_name "Live Words") (test_name "[Null] Live Words")
      (value 14540756.) (value_type Float))
     ((group_name "Live Words") (test_name "[Clean] Live Words")
      (value 14521522.) (value_type Float))
     ((group_name "Live Words") (test_name "[Clean Sandbox] Live Words")
      (value 14521554.) (value_type Float))
     ((group_name "Promoted Words") (test_name "[Null] Promoted Words")
      (value 16338845.6) (value_type Float))
     ((group_name "Promoted Words")
      (test_name "[Clean Sandbox] Promoted Words") (value 29598829.)
      (value_type Float))
     ((group_name "Promoted Words") (test_name "[Null Sandbox] Promoted Words")
      (value 16336944.4) (value_type Float))
     ((group_name "Promoted Words") (test_name "[Clean] Promoted Words")
      (value 28402995.) (value_type Float))
     ((group_name "Minor Collections")
      (test_name "[Null Sandbox] Minor Collections") (value 709.)
      (value_type Float))
     ((group_name "Minor Collections") (test_name "[Clean] Minor Collections")
      (value 942.) (value_type Float))
     ((group_name "Minor Collections") (test_name "[Null] Minor Collections")
      (value 711.) (value_type Float))
     ((group_name "Minor Collections")
      (test_name "[Clean Sandbox] Minor Collections") (value 990.)
      (value_type Float))
     ((group_name Compactions) (test_name "[Null] Compactions") (value 1.)
      (value_type Float))
     ((group_name Compactions) (test_name "[Clean Sandbox] Compactions")
      (value 1.) (value_type Float))
     ((group_name Compactions) (test_name "[Null Sandbox] Compactions")
      (value 1.) (value_type Float))
     ((group_name Compactions) (test_name "[Clean] Compactions") (value 1.)
      (value_type Float))
     ((group_name "Top Heap Words") (test_name "[Null Sandbox] Top Heap Words")
      (value 16876032.) (value_type Float))
     ((group_name "Top Heap Words") (test_name "[Clean] Top Heap Words")
      (value 21820416.) (value_type Float))
     ((group_name "Top Heap Words")
      (test_name "[Clean Sandbox] Top Heap Words") (value 21820416.)
      (value_type Float))
     ((group_name "Top Heap Words") (test_name "[Null] Top Heap Words")
      (value 16876032.) (value_type Float))
     ((group_name "Heap Words") (test_name "[Null] Heap Words")
      (value 16876032.) (value_type Float))
     ((group_name "Heap Words") (test_name "[Null Sandbox] Heap Words")
      (value 16876032.) (value_type Float))
     ((group_name "Heap Words") (test_name "[Clean] Heap Words")
      (value 21820416.) (value_type Float))
     ((group_name "Heap Words") (test_name "[Clean Sandbox] Heap Words")
      (value 21820416.) (value_type Float)))))
